### ISSUE TITLE
Provide size of input (bytes)

### ISSUE THREAD

**Issue by jgstew** [Miserlou/omnihash#13]
particularly in the case of files / URL contents, it would be useful if this could also output the size of the input at the end.

This is particularly useful if I want to hash a file from a URL in the case where I don't know the size already and I don't want to download it twice to find both the size and the hash.

**Comment by Miserlou** [comment]
+1, feel free to send PR. Thanks for using oh!

**Comment by Miserlou** [comment]
If you do get a chance to tackle this one, it'd be great if you could also make sure the output is properly formatted in the JSON output as well with `bytes`, `type` and `name` fields.

**Comment by Miserlou** [comment]
Gonna handle this one, @jgstew :-)

**Comment by jgstew** [comment]
Probably not anytime soon. I haven't started playing with Omnihash yet. 

I did install it with PIP but I was having trouble figuring out how to run it directly.

**Comment by ankostis** [comment]
Would you like to explain what is the problem?
*pip* should install 2 executables in your path: `omnihash` and `oh`

**Comment by jgstew** [comment]
what is the relative path that `oh` and `omnihash` executables should be installed under? They don't seem to be in my path.

**Comment by ankostis** [comment]
I guess you have git cloned the repo and you need to run the command from the sources, correct?

You have to install the project in "develop" mode. Cd to project s folder and type:

    pip install -e .

**Comment by jgstew** [comment]
That is not the case, I figured it out here: https://github.com/Miserlou/omnihash/issues/18

`pip` is also not in my path, and omnihash is in the same folder, so it is specific to my config.
