### ISSUE TITLE
Specify specific hashing algorithms

### ISSUE THREAD

**Issue by jgstew** [Miserlou/omnihash#14]
it would be useful to limit the output / computation to a particular set of hashing algorithms.

For instance, I might only want: MD5, SHA1, SHA256

If there was an option to provide a list of digesters, that would be useful.

**Comment by Miserlou** [comment]
+1, already discussed and accepted as a feature request here: https://github.com/Miserlou/omnihash/issues/10

Again, feel free to send a PR!

**Comment by jgstew** [comment]
Now that I read through that issue, I do see that it is in there. It wasn't obvious to me from the name of that issue that it was about something similar.

I'll send a PR if I end up going down this path. I filed the issue because I'm thinking about it.

**Comment by jgstew** [comment]
neat!
